---
version: "3.8"
services:
  chrome:
    image: selenium/standalone-chrome
    restart: always
    ports:
      - 4444:4444
    networks:
      - app-network
  fizzstockalert:
    build:
        context: .
        dockerfile: FizzStockAlert/Dockerfile
    restart: always
    depends_on:
      - chrome
    environment:
      - CHROME_HOST=chrome
    networks:
      - app-network

      
networks:
   app-network:
    driver: bridge
